apiVersion: v1
kind: Service
metadata:
  name: tellurion
  labels:
    app.kubernetes.io/name: tellurion
spec:
  selector:
    app.kubernetes.io/name: tellurion
  ports:
    - name: http
      port: 8080
      targetPort: http
