//! Regenerates `tests/fixtures/tiny.fgb`, the committed test archive: five
//! real point features (WGS84/CRS84, `crs.code = 4326`) spread across a
//! small bbox, each carrying a `name`/`value` property pair, written with
//! the crate's default options (indexed, Hilbert-sorted). Run with:
//!
//! ```sh
//! cargo run -p tellurion-flatgeobuf --example gen_flatgeobuf_fixture
//! ```
//!
//! Unlike `tellurion-pmtiles`' fixture generator, this needs no separate
//! cargo feature to isolate a write path: `flatgeobuf`'s `FgbWriter` ships
//! in the base crate unconditionally (no upstream `write` feature gate to
//! keep out of the normal build graph), so this example carries no extra
//! weight for a plain `cargo build`/`cargo test` of the driver crate.

use std::fs::File;
use std::io::BufWriter;
use std::path::PathBuf;

use flatgeobuf::{ColumnType, FgbCrs, FgbWriter, FgbWriterOptions, GeometryType};
use geozero::geojson::GeoJson;

/// `(name, value, longitude, latitude)` — five points spanning roughly the
/// same bbox `tellurion-pmtiles`' own fixture uses, for family resemblance
/// between the two file-driver fixtures.
const FEATURES: [(&str, i64, f64, f64); 5] = [
    ("alpha", 1, -4.0, 46.0),
    ("bravo", 2, -2.0, 48.0),
    ("charlie", 3, 0.0, 50.0),
    ("delta", 4, 2.0, 52.0),
    ("echo", 5, 4.0, 54.0),
];

fn main() {
    let out_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/tiny.fgb");

    let options = FgbWriterOptions {
        crs: FgbCrs {
            code: 4326,
            ..Default::default()
        },
        description: Some(
            "tellurion-flatgeobuf test fixture — generated by examples/gen_flatgeobuf_fixture.rs",
        ),
        ..Default::default()
    };
    let mut fgb = FgbWriter::create_with_options("demo", GeometryType::Point, options)
        .expect("creates the flatgeobuf writer");

    // `FgbWriter::add_feature` writes properties straight into its
    // per-feature `FeatureWriter`, not through `FgbWriter` itself — the
    // column auto-declaration path on `impl PropertyProcessor for
    // FgbWriter` (see upstream's `file_writer.rs`) only fires when a whole
    // `GeozeroDatasource` is driven through the writer directly (the
    // crate's own "Writing a FlatGeobuf file" doc example). Declaring the
    // schema explicitly here is simpler than restructuring this generator
    // around that alternate entry point, and produces a fixture with an
    // honest, intentional column schema rather than an inferred one.
    fgb.add_column("name", ColumnType::String, |_, _| {});
    fgb.add_column("value", ColumnType::Long, |_, _| {});

    for (name, value, lon, lat) in FEATURES {
        let geojson = format!(
            r#"{{"type":"Feature","properties":{{"name":"{name}","value":{value}}},"geometry":{{"type":"Point","coordinates":[{lon},{lat}]}}}}"#
        );
        fgb.add_feature(GeoJson(&geojson))
            .unwrap_or_else(|err| panic!("adds feature '{name}': {err}"));
    }

    let file = File::create(&out_path).expect("creates the fixture file");
    fgb.write(BufWriter::new(file))
        .expect("writes the flatgeobuf file");

    let size = std::fs::metadata(&out_path).unwrap().len();
    println!("wrote {} ({} bytes)", out_path.display(), size);
}
