//! Regenerates `tests/fixtures/tiny.pmtiles`, the committed test archive:
//! three real, valid MVT tiles (z0/0/0, z1/1/0, z2/2/1 — WMTS z/x/y, top-left
//! origin) over a small bbox, gzip-compressed exactly as a real archive
//! would be. Run with:
//!
//! ```sh
//! cargo run -p tellurion-pmtiles --example gen_fixture --features fixture-gen
//! ```
//!
//! Only this example (and the `fixture-gen` feature it requires) links the
//! crate's write path — the driver itself is read-only (see `src/driver.rs`).

use std::fs::File;
use std::path::PathBuf;

use geozero::mvt::{tile, Message, Tile};
use pmtiles::{Compression, PmTilesWriter, TileCoord, TileType};

/// A minimal, genuinely valid single-point MVT tile — same construction
/// tellurion-tiles' own test suite uses (`crates/tellurion-tiles/src/
/// handlers.rs`'s `valid_mvt_bytes_named`), so every tile in this fixture
/// round-trips through a real vector-tile decoder, not just arbitrary bytes.
fn mvt_tile(layer_name: &str) -> Vec<u8> {
    let mut layer = tile::Layer {
        version: 2,
        name: layer_name.to_string(),
        extent: Some(4096),
        ..Default::default()
    };
    let mut feature = tile::Feature {
        geometry: vec![9, 50, 34],
        ..Default::default()
    };
    feature.set_type(tile::GeomType::Point);
    layer.features.push(feature);
    Tile {
        layers: vec![layer],
    }
    .encode_to_vec()
}

fn main() {
    let out_path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/tiny.pmtiles");

    let metadata = serde_json::json!({
        "name": "demo",
        "description": "tellurion-pmtiles test fixture — generated by examples/gen_fixture.rs",
        // The TileJSON-convention field real generators (tippecanoe, mbutil,
        // ...) write to self-describe an archive's real MVT layer names —
        // deliberately unrelated to the "name" above (and to whatever
        // collection id a deployment configures for this archive), so tests
        // reading it prove they use the archive's own metadata rather than
        // assuming the layer name equals the collection id (#49).
        "vector_layers": [
            { "id": "world" },
            { "id": "quadrant" },
            { "id": "leaf" },
        ],
    })
    .to_string();

    let file = File::create(&out_path).expect("creates the fixture file");
    let mut writer = PmTilesWriter::new(TileType::Mvt)
        .tile_compression(Compression::Gzip)
        .min_zoom(0)
        .max_zoom(2)
        .bounds(-5.0, 45.0, 5.0, 55.0)
        .center(0.0, 50.0)
        .center_zoom(1)
        .metadata(&metadata)
        .create(file)
        .expect("creates the pmtiles writer");

    writer
        .add_tile(TileCoord::new(0, 0, 0).unwrap(), &mvt_tile("world"))
        .expect("adds the z0 tile");
    writer
        .add_tile(TileCoord::new(1, 1, 0).unwrap(), &mvt_tile("quadrant"))
        .expect("adds the z1 tile");
    writer
        .add_tile(TileCoord::new(2, 2, 1).unwrap(), &mvt_tile("leaf"))
        .expect("adds the z2 tile");

    writer.finalize().expect("finalizes the archive");

    let size = std::fs::metadata(&out_path).unwrap().len();
    println!("wrote {} ({} bytes)", out_path.display(), size);
}
